env: prod
log_level: debug

http_server:
  host: localhost
  port: 8000
  read_timeout: 30s
  write_timeout: 30s
  swagger_enabled: true

postgres:
  conn_string: # POSTGRES_CONN_STRING
  ping_timeout: 5s
  max_idle_lifetime: 10s
  max_conn_lifetime: 5m
  max_conn_amount: 30
  min_conn_amount: 5

minio_s3:
  endpoint: localhost:9000
  root_user: # MINIO_ROOT_USER
  root_password: # MINIO_ROOT_PASSWORD
  use_ssl: false
  bucket_name: humpback-whale-image

ml_recognizer_http:
#  host: http://localhost:8001/api/v1
  host: http://localhost:8001/api/v1
  timeout: 5s
  backoff_timeout: 100ms
  backoff_timeout_max: 700ms
  retry_max: 3
  max_idle_conns: 100
  max_conns_per_host: 100
  max_idle_conns_per_host: 100
  circuit_breaker:
    min_threshold: 20
    failure_rate: 60
    reset_interval: 10s
    half_open_max_successes: 5
    backoff_initial_interval: 1s
    backoff_multiplier: 2.0
    backoff_max_interval: 6s

jwt_generator:
  signing_key: # JWT_SIGNING_KEY
  ttl: 24h

get_images_uc:
#  url_page_template: http://localhost:8000/api/v1/public/whale/images?limit={limit}&cursor={cursor} #local
  url_page_template: http://localhost:80/api/v1/public/whale/images?limit={limit}&cursor={cursor}
