// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "humpback-whale",
            "url": "https://github.com/OkDenAl/humback-whale"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/private/whale/types/{whale_type_id}": {
            "delete": {
                "description": "Deletes a whale type record.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale Types"
                ],
                "summary": "Delete a whale type",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Whale Type ID (UUID)",
                        "name": "whale_type_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid Whale Type ID format",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/private/whale/update": {
            "post": {
                "description": "update images info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale"
                ],
                "summary": "update images info",
                "parameters": [
                    {
                        "description": "Req body json",
                        "name": "limit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.updateImageInfoReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/private/whale/upload": {
            "post": {
                "description": "upload whale image",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale"
                ],
                "summary": "upload whale image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Latitude",
                        "name": "latitude",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Longitude",
                        "name": "longitude",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Saw at",
                        "name": "saw_at",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "authorization bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.uploadImgResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/private/whale/{whale_id}": {
            "delete": {
                "description": "Deletes a whale image record and the corresponding image file from storage.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale"
                ],
                "summary": "Delete a whale image",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Whale Image ID (UUID)",
                        "name": "whale_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid Whale ID format",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "404": {
                        "description": "Whale image not found",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/public/auth/login": {
            "post": {
                "description": "login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "login user",
                "parameters": [
                    {
                        "description": "JSON",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.reqLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.respLogin"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/public/auth/register": {
            "post": {
                "description": "register user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "register user",
                "parameters": [
                    {
                        "description": "JSON",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.reqRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.respRegister"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/public/auth/reset-password": {
            "post": {
                "description": "reset password using token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "description": "JSON",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.resetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.resetPasswordResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/public/auth/send-reset-password": {
            "post": {
                "description": "send reset password email to user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "send reset password email",
                "parameters": [
                    {
                        "description": "JSON",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.sendResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.sendResetPasswordResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/public/whale/images": {
            "get": {
                "description": "get whale images with pagination and filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale"
                ],
                "summary": "get images with filters",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp cursor (RFC3339Nano format) for pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by author username",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by whale type id",
                        "name": "whale_type_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start time (RFC3339Nano format)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end time (RFC3339Nano format)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with whale images",
                        "schema": {
                            "$ref": "#/definitions/handler.getImagesResp"
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid parameters)",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "404": {
                        "description": "Not found (no images match filters)",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        },
        "/public/whale/types": {
            "get": {
                "description": "Get a list of all available whale types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale Types"
                ],
                "summary": "get all whale types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.getWhaleTypesResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whale Types"
                ],
                "summary": "create whale type or update existing whale type",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.httpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "getimages.HumpbackWhaleImage": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "saw_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "whale_type": {
                    "$ref": "#/definitions/getimages.WhaleType"
                }
            }
        },
        "getimages.WhaleType": {
            "type": "object",
            "properties": {
                "conservation_status": {
                    "type": "string"
                },
                "family": {
                    "type": "string"
                },
                "genus": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "species_eng": {
                    "type": "string"
                },
                "species_rus": {
                    "type": "string"
                }
            }
        },
        "getwhaletypes.WhaleType": {
            "type": "object",
            "properties": {
                "conservation_status": {
                    "type": "string"
                },
                "family": {
                    "type": "string"
                },
                "genus": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "species_eng": {
                    "type": "string"
                },
                "species_rus": {
                    "type": "string"
                }
            }
        },
        "handler.getImagesResp": {
            "type": "object",
            "properties": {
                "next_page_url": {
                    "type": "string"
                },
                "prev_page_url": {
                    "type": "string"
                },
                "whale_images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/getimages.HumpbackWhaleImage"
                    }
                }
            }
        },
        "handler.getWhaleTypesResp": {
            "type": "object",
            "properties": {
                "whale_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/getwhaletypes.WhaleType"
                    }
                }
            }
        },
        "handler.httpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.reqLogin": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.reqRegister": {
            "type": "object",
            "properties": {
                "degree": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "place_of_work": {
                    "type": "string"
                },
                "rank": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.resetPasswordRequest": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "handler.resetPasswordResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.respLogin": {
            "type": "object",
            "properties": {
                "is_scientist": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.respRegister": {
            "type": "object",
            "properties": {
                "is_scientist": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.sendResetPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "handler.sendResetPasswordResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.updateImageInfoReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "whale_type": {
                    "type": "string"
                }
            }
        },
        "handler.uploadImgResp": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Humpback whale recognition service",
	Description:      "Humpback whale recognition - it is the service for recognize humpback whale and store it in catalog.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
