basePath: /api/v1
definitions:
  getimages.HumpbackWhaleImage:
    properties:
      author_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      gender:
        type: string
      id:
        type: string
      image_url:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
      saw_at:
        type: string
      username:
        type: string
      whale_type:
        $ref: '#/definitions/getimages.WhaleType'
    type: object
  getimages.WhaleType:
    properties:
      conservation_status:
        type: string
      family:
        type: string
      genus:
        type: string
      id:
        type: string
      species_eng:
        type: string
      species_rus:
        type: string
    type: object
  getwhaletypes.WhaleType:
    properties:
      conservation_status:
        type: string
      family:
        type: string
      genus:
        type: string
      id:
        type: string
      species_eng:
        type: string
      species_rus:
        type: string
    type: object
  handler.getImagesResp:
    properties:
      next_page_url:
        type: string
      prev_page_url:
        type: string
      whale_images:
        items:
          $ref: '#/definitions/getimages.HumpbackWhaleImage'
        type: array
    type: object
  handler.getWhaleTypesResp:
    properties:
      whale_types:
        items:
          $ref: '#/definitions/getwhaletypes.WhaleType'
        type: array
    type: object
  handler.httpError:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  handler.reqLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.reqRegister:
    properties:
      degree:
        type: string
      email:
        type: string
      password:
        type: string
      place_of_work:
        type: string
      rank:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  handler.resetPasswordRequest:
    properties:
      password:
        type: string
      token:
        type: string
    required:
    - password
    - token
    type: object
  handler.resetPasswordResp:
    properties:
      message:
        type: string
    type: object
  handler.respLogin:
    properties:
      is_scientist:
        type: boolean
      token:
        type: string
      username:
        type: string
    type: object
  handler.respRegister:
    properties:
      is_scientist:
        type: boolean
      token:
        type: string
      username:
        type: string
    type: object
  handler.sendResetPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  handler.sendResetPasswordResp:
    properties:
      message:
        type: string
    type: object
  handler.updateImageInfoReq:
    properties:
      description:
        type: string
      gender:
        type: string
      name:
        type: string
      whale_type:
        type: string
    type: object
  handler.uploadImgResp:
    properties:
      url:
        type: string
    type: object
host: localhost:80
info:
  contact:
    name: humpback-whale
    url: https://github.com/OkDenAl/humback-whale
  description: Humpback whale recognition - it is the service for recognize humpback
    whale and store it in catalog.
  title: Humpback whale recognition service
  version: "1.0"
paths:
  /private/whale/{whale_id}:
    delete:
      description: Deletes a whale image record and the corresponding image file from
        storage.
      parameters:
      - default: Bearer <token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Whale Image ID (UUID)
        in: path
        name: whale_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid Whale ID format
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "404":
          description: Whale image not found
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: Delete a whale image
      tags:
      - Whale
  /private/whale/types/{whale_type_id}:
    delete:
      description: Deletes a whale type record.
      parameters:
      - default: Bearer <token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Whale Type ID (UUID)
        in: path
        name: whale_type_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid Whale Type ID format
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: Delete a whale type
      tags:
      - Whale Types
  /private/whale/update:
    post:
      description: update images info
      parameters:
      - description: Req body json
        in: body
        name: limit
        required: true
        schema:
          $ref: '#/definitions/handler.updateImageInfoReq'
      - description: authorization bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: update images info
      tags:
      - Whale
  /private/whale/upload:
    post:
      consumes:
      - multipart/form-data
      description: upload whale image
      parameters:
      - description: File to upload
        in: formData
        name: image
        required: true
        type: file
      - description: Latitude
        in: formData
        name: latitude
        type: number
      - description: Longitude
        in: formData
        name: longitude
        type: number
      - description: Saw at
        in: formData
        name: saw_at
        type: number
      - description: authorization bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.uploadImgResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: upload whale image
      tags:
      - Whale
  /public/auth/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: JSON
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/handler.reqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.respLogin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: login user
      tags:
      - Auth
  /public/auth/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: JSON
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/handler.reqRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.respRegister'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: register user
      tags:
      - Auth
  /public/auth/reset-password:
    post:
      consumes:
      - application/json
      description: reset password using token
      parameters:
      - description: JSON
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/handler.resetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.resetPasswordResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: reset password
      tags:
      - Auth
  /public/auth/send-reset-password:
    post:
      consumes:
      - application/json
      description: send reset password email to user
      parameters:
      - description: JSON
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/handler.sendResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.sendResetPasswordResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: send reset password email
      tags:
      - Auth
  /public/whale/images:
    get:
      description: get whale images with pagination and filters
      parameters:
      - description: Limit per page
        in: query
        name: limit
        required: true
        type: integer
      - description: Timestamp cursor (RFC3339Nano format) for pagination
        in: query
        name: cursor
        type: string
      - description: Filter by author username
        in: query
        name: username
        type: string
      - description: Filter by whale type id
        in: query
        name: whale_type_id
        type: string
      - description: Filter by start time (RFC3339Nano format)
        in: query
        name: start_time
        type: string
      - description: Filter by end time (RFC3339Nano format)
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with whale images
          schema:
            $ref: '#/definitions/handler.getImagesResp'
        "400":
          description: Bad request (invalid parameters)
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "404":
          description: Not found (no images match filters)
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: get images with filters
      tags:
      - Whale
  /public/whale/types:
    get:
      description: Get a list of all available whale types
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getWhaleTypesResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: get all whale types
      tags:
      - Whale Types
    post:
      parameters:
      - default: Bearer <token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.httpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.httpError'
      summary: create whale type or update existing whale type
      tags:
      - Whale Types
swagger: "2.0"
