package miniorepo

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"io"
	"net/url"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/minio/minio-go/v7"
)

// IMinioClientMock implements miniorepo.iMinioClient
type IMinioClientMock struct {
	t minimock.Tester

	funcPresignedGetObject          func(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values) (up1 *url.URL, err error)
	inspectFuncPresignedGetObject   func(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values)
	afterPresignedGetObjectCounter  uint64
	beforePresignedGetObjectCounter uint64
	PresignedGetObjectMock          mIMinioClientMockPresignedGetObject

	funcPutObject          func(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (u1 minio.UploadInfo, err error)
	inspectFuncPutObject   func(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions)
	afterPutObjectCounter  uint64
	beforePutObjectCounter uint64
	PutObjectMock          mIMinioClientMockPutObject

	funcRemoveObject          func(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions) (err error)
	inspectFuncRemoveObject   func(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions)
	afterRemoveObjectCounter  uint64
	beforeRemoveObjectCounter uint64
	RemoveObjectMock          mIMinioClientMockRemoveObject
}

// NewIMinioClientMock returns a mock for miniorepo.iMinioClient
func NewIMinioClientMock(t minimock.Tester) *IMinioClientMock {
	m := &IMinioClientMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PresignedGetObjectMock = mIMinioClientMockPresignedGetObject{mock: m}
	m.PresignedGetObjectMock.callArgs = []*IMinioClientMockPresignedGetObjectParams{}

	m.PutObjectMock = mIMinioClientMockPutObject{mock: m}
	m.PutObjectMock.callArgs = []*IMinioClientMockPutObjectParams{}

	m.RemoveObjectMock = mIMinioClientMockRemoveObject{mock: m}
	m.RemoveObjectMock.callArgs = []*IMinioClientMockRemoveObjectParams{}

	return m
}

type mIMinioClientMockPresignedGetObject struct {
	mock               *IMinioClientMock
	defaultExpectation *IMinioClientMockPresignedGetObjectExpectation
	expectations       []*IMinioClientMockPresignedGetObjectExpectation

	callArgs []*IMinioClientMockPresignedGetObjectParams
	mutex    sync.RWMutex
}

// IMinioClientMockPresignedGetObjectExpectation specifies expectation struct of the iMinioClient.PresignedGetObject
type IMinioClientMockPresignedGetObjectExpectation struct {
	mock    *IMinioClientMock
	params  *IMinioClientMockPresignedGetObjectParams
	results *IMinioClientMockPresignedGetObjectResults
	Counter uint64
}

// IMinioClientMockPresignedGetObjectParams contains parameters of the iMinioClient.PresignedGetObject
type IMinioClientMockPresignedGetObjectParams struct {
	ctx        context.Context
	bucketName string
	objectName string
	expires    time.Duration
	reqParams  url.Values
}

// IMinioClientMockPresignedGetObjectResults contains results of the iMinioClient.PresignedGetObject
type IMinioClientMockPresignedGetObjectResults struct {
	up1 *url.URL
	err error
}

// Expect sets up expected params for iMinioClient.PresignedGetObject
func (mmPresignedGetObject *mIMinioClientMockPresignedGetObject) Expect(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values) *mIMinioClientMockPresignedGetObject {
	if mmPresignedGetObject.mock.funcPresignedGetObject != nil {
		mmPresignedGetObject.mock.t.Fatalf("IMinioClientMock.PresignedGetObject mock is already set by Set")
	}

	if mmPresignedGetObject.defaultExpectation == nil {
		mmPresignedGetObject.defaultExpectation = &IMinioClientMockPresignedGetObjectExpectation{}
	}

	mmPresignedGetObject.defaultExpectation.params = &IMinioClientMockPresignedGetObjectParams{ctx, bucketName, objectName, expires, reqParams}
	for _, e := range mmPresignedGetObject.expectations {
		if minimock.Equal(e.params, mmPresignedGetObject.defaultExpectation.params) {
			mmPresignedGetObject.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPresignedGetObject.defaultExpectation.params)
		}
	}

	return mmPresignedGetObject
}

// Inspect accepts an inspector function that has same arguments as the iMinioClient.PresignedGetObject
func (mmPresignedGetObject *mIMinioClientMockPresignedGetObject) Inspect(f func(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values)) *mIMinioClientMockPresignedGetObject {
	if mmPresignedGetObject.mock.inspectFuncPresignedGetObject != nil {
		mmPresignedGetObject.mock.t.Fatalf("Inspect function is already set for IMinioClientMock.PresignedGetObject")
	}

	mmPresignedGetObject.mock.inspectFuncPresignedGetObject = f

	return mmPresignedGetObject
}

// Return sets up results that will be returned by iMinioClient.PresignedGetObject
func (mmPresignedGetObject *mIMinioClientMockPresignedGetObject) Return(up1 *url.URL, err error) *IMinioClientMock {
	if mmPresignedGetObject.mock.funcPresignedGetObject != nil {
		mmPresignedGetObject.mock.t.Fatalf("IMinioClientMock.PresignedGetObject mock is already set by Set")
	}

	if mmPresignedGetObject.defaultExpectation == nil {
		mmPresignedGetObject.defaultExpectation = &IMinioClientMockPresignedGetObjectExpectation{mock: mmPresignedGetObject.mock}
	}
	mmPresignedGetObject.defaultExpectation.results = &IMinioClientMockPresignedGetObjectResults{up1, err}
	return mmPresignedGetObject.mock
}

// Set uses given function f to mock the iMinioClient.PresignedGetObject method
func (mmPresignedGetObject *mIMinioClientMockPresignedGetObject) Set(f func(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values) (up1 *url.URL, err error)) *IMinioClientMock {
	if mmPresignedGetObject.defaultExpectation != nil {
		mmPresignedGetObject.mock.t.Fatalf("Default expectation is already set for the iMinioClient.PresignedGetObject method")
	}

	if len(mmPresignedGetObject.expectations) > 0 {
		mmPresignedGetObject.mock.t.Fatalf("Some expectations are already set for the iMinioClient.PresignedGetObject method")
	}

	mmPresignedGetObject.mock.funcPresignedGetObject = f
	return mmPresignedGetObject.mock
}

// When sets expectation for the iMinioClient.PresignedGetObject which will trigger the result defined by the following
// Then helper
func (mmPresignedGetObject *mIMinioClientMockPresignedGetObject) When(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values) *IMinioClientMockPresignedGetObjectExpectation {
	if mmPresignedGetObject.mock.funcPresignedGetObject != nil {
		mmPresignedGetObject.mock.t.Fatalf("IMinioClientMock.PresignedGetObject mock is already set by Set")
	}

	expectation := &IMinioClientMockPresignedGetObjectExpectation{
		mock:   mmPresignedGetObject.mock,
		params: &IMinioClientMockPresignedGetObjectParams{ctx, bucketName, objectName, expires, reqParams},
	}
	mmPresignedGetObject.expectations = append(mmPresignedGetObject.expectations, expectation)
	return expectation
}

// Then sets up iMinioClient.PresignedGetObject return parameters for the expectation previously defined by the When method
func (e *IMinioClientMockPresignedGetObjectExpectation) Then(up1 *url.URL, err error) *IMinioClientMock {
	e.results = &IMinioClientMockPresignedGetObjectResults{up1, err}
	return e.mock
}

// PresignedGetObject implements miniorepo.iMinioClient
func (mmPresignedGetObject *IMinioClientMock) PresignedGetObject(ctx context.Context, bucketName string, objectName string, expires time.Duration, reqParams url.Values) (up1 *url.URL, err error) {
	mm_atomic.AddUint64(&mmPresignedGetObject.beforePresignedGetObjectCounter, 1)
	defer mm_atomic.AddUint64(&mmPresignedGetObject.afterPresignedGetObjectCounter, 1)

	if mmPresignedGetObject.inspectFuncPresignedGetObject != nil {
		mmPresignedGetObject.inspectFuncPresignedGetObject(ctx, bucketName, objectName, expires, reqParams)
	}

	mm_params := &IMinioClientMockPresignedGetObjectParams{ctx, bucketName, objectName, expires, reqParams}

	// Record call args
	mmPresignedGetObject.PresignedGetObjectMock.mutex.Lock()
	mmPresignedGetObject.PresignedGetObjectMock.callArgs = append(mmPresignedGetObject.PresignedGetObjectMock.callArgs, mm_params)
	mmPresignedGetObject.PresignedGetObjectMock.mutex.Unlock()

	for _, e := range mmPresignedGetObject.PresignedGetObjectMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmPresignedGetObject.PresignedGetObjectMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPresignedGetObject.PresignedGetObjectMock.defaultExpectation.Counter, 1)
		mm_want := mmPresignedGetObject.PresignedGetObjectMock.defaultExpectation.params
		mm_got := IMinioClientMockPresignedGetObjectParams{ctx, bucketName, objectName, expires, reqParams}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPresignedGetObject.t.Errorf("IMinioClientMock.PresignedGetObject got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPresignedGetObject.PresignedGetObjectMock.defaultExpectation.results
		if mm_results == nil {
			mmPresignedGetObject.t.Fatal("No results are set for the IMinioClientMock.PresignedGetObject")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmPresignedGetObject.funcPresignedGetObject != nil {
		return mmPresignedGetObject.funcPresignedGetObject(ctx, bucketName, objectName, expires, reqParams)
	}
	mmPresignedGetObject.t.Fatalf("Unexpected call to IMinioClientMock.PresignedGetObject. %v %v %v %v %v", ctx, bucketName, objectName, expires, reqParams)
	return
}

// PresignedGetObjectAfterCounter returns a count of finished IMinioClientMock.PresignedGetObject invocations
func (mmPresignedGetObject *IMinioClientMock) PresignedGetObjectAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPresignedGetObject.afterPresignedGetObjectCounter)
}

// PresignedGetObjectBeforeCounter returns a count of IMinioClientMock.PresignedGetObject invocations
func (mmPresignedGetObject *IMinioClientMock) PresignedGetObjectBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPresignedGetObject.beforePresignedGetObjectCounter)
}

// Calls returns a list of arguments used in each call to IMinioClientMock.PresignedGetObject.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPresignedGetObject *mIMinioClientMockPresignedGetObject) Calls() []*IMinioClientMockPresignedGetObjectParams {
	mmPresignedGetObject.mutex.RLock()

	argCopy := make([]*IMinioClientMockPresignedGetObjectParams, len(mmPresignedGetObject.callArgs))
	copy(argCopy, mmPresignedGetObject.callArgs)

	mmPresignedGetObject.mutex.RUnlock()

	return argCopy
}

// MinimockPresignedGetObjectDone returns true if the count of the PresignedGetObject invocations corresponds
// the number of defined expectations
func (m *IMinioClientMock) MinimockPresignedGetObjectDone() bool {
	for _, e := range m.PresignedGetObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PresignedGetObjectMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPresignedGetObjectCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPresignedGetObject != nil && mm_atomic.LoadUint64(&m.afterPresignedGetObjectCounter) < 1 {
		return false
	}
	return true
}

// MinimockPresignedGetObjectInspect logs each unmet expectation
func (m *IMinioClientMock) MinimockPresignedGetObjectInspect() {
	for _, e := range m.PresignedGetObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IMinioClientMock.PresignedGetObject with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PresignedGetObjectMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPresignedGetObjectCounter) < 1 {
		if m.PresignedGetObjectMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IMinioClientMock.PresignedGetObject")
		} else {
			m.t.Errorf("Expected call to IMinioClientMock.PresignedGetObject with params: %#v", *m.PresignedGetObjectMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPresignedGetObject != nil && mm_atomic.LoadUint64(&m.afterPresignedGetObjectCounter) < 1 {
		m.t.Error("Expected call to IMinioClientMock.PresignedGetObject")
	}
}

type mIMinioClientMockPutObject struct {
	mock               *IMinioClientMock
	defaultExpectation *IMinioClientMockPutObjectExpectation
	expectations       []*IMinioClientMockPutObjectExpectation

	callArgs []*IMinioClientMockPutObjectParams
	mutex    sync.RWMutex
}

// IMinioClientMockPutObjectExpectation specifies expectation struct of the iMinioClient.PutObject
type IMinioClientMockPutObjectExpectation struct {
	mock    *IMinioClientMock
	params  *IMinioClientMockPutObjectParams
	results *IMinioClientMockPutObjectResults
	Counter uint64
}

// IMinioClientMockPutObjectParams contains parameters of the iMinioClient.PutObject
type IMinioClientMockPutObjectParams struct {
	ctx        context.Context
	bucketName string
	objectName string
	reader     io.Reader
	objectSize int64
	opts       minio.PutObjectOptions
}

// IMinioClientMockPutObjectResults contains results of the iMinioClient.PutObject
type IMinioClientMockPutObjectResults struct {
	u1  minio.UploadInfo
	err error
}

// Expect sets up expected params for iMinioClient.PutObject
func (mmPutObject *mIMinioClientMockPutObject) Expect(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) *mIMinioClientMockPutObject {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("IMinioClientMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &IMinioClientMockPutObjectExpectation{}
	}

	mmPutObject.defaultExpectation.params = &IMinioClientMockPutObjectParams{ctx, bucketName, objectName, reader, objectSize, opts}
	for _, e := range mmPutObject.expectations {
		if minimock.Equal(e.params, mmPutObject.defaultExpectation.params) {
			mmPutObject.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPutObject.defaultExpectation.params)
		}
	}

	return mmPutObject
}

// Inspect accepts an inspector function that has same arguments as the iMinioClient.PutObject
func (mmPutObject *mIMinioClientMockPutObject) Inspect(f func(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions)) *mIMinioClientMockPutObject {
	if mmPutObject.mock.inspectFuncPutObject != nil {
		mmPutObject.mock.t.Fatalf("Inspect function is already set for IMinioClientMock.PutObject")
	}

	mmPutObject.mock.inspectFuncPutObject = f

	return mmPutObject
}

// Return sets up results that will be returned by iMinioClient.PutObject
func (mmPutObject *mIMinioClientMockPutObject) Return(u1 minio.UploadInfo, err error) *IMinioClientMock {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("IMinioClientMock.PutObject mock is already set by Set")
	}

	if mmPutObject.defaultExpectation == nil {
		mmPutObject.defaultExpectation = &IMinioClientMockPutObjectExpectation{mock: mmPutObject.mock}
	}
	mmPutObject.defaultExpectation.results = &IMinioClientMockPutObjectResults{u1, err}
	return mmPutObject.mock
}

// Set uses given function f to mock the iMinioClient.PutObject method
func (mmPutObject *mIMinioClientMockPutObject) Set(f func(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (u1 minio.UploadInfo, err error)) *IMinioClientMock {
	if mmPutObject.defaultExpectation != nil {
		mmPutObject.mock.t.Fatalf("Default expectation is already set for the iMinioClient.PutObject method")
	}

	if len(mmPutObject.expectations) > 0 {
		mmPutObject.mock.t.Fatalf("Some expectations are already set for the iMinioClient.PutObject method")
	}

	mmPutObject.mock.funcPutObject = f
	return mmPutObject.mock
}

// When sets expectation for the iMinioClient.PutObject which will trigger the result defined by the following
// Then helper
func (mmPutObject *mIMinioClientMockPutObject) When(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) *IMinioClientMockPutObjectExpectation {
	if mmPutObject.mock.funcPutObject != nil {
		mmPutObject.mock.t.Fatalf("IMinioClientMock.PutObject mock is already set by Set")
	}

	expectation := &IMinioClientMockPutObjectExpectation{
		mock:   mmPutObject.mock,
		params: &IMinioClientMockPutObjectParams{ctx, bucketName, objectName, reader, objectSize, opts},
	}
	mmPutObject.expectations = append(mmPutObject.expectations, expectation)
	return expectation
}

// Then sets up iMinioClient.PutObject return parameters for the expectation previously defined by the When method
func (e *IMinioClientMockPutObjectExpectation) Then(u1 minio.UploadInfo, err error) *IMinioClientMock {
	e.results = &IMinioClientMockPutObjectResults{u1, err}
	return e.mock
}

// PutObject implements miniorepo.iMinioClient
func (mmPutObject *IMinioClientMock) PutObject(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (u1 minio.UploadInfo, err error) {
	mm_atomic.AddUint64(&mmPutObject.beforePutObjectCounter, 1)
	defer mm_atomic.AddUint64(&mmPutObject.afterPutObjectCounter, 1)

	if mmPutObject.inspectFuncPutObject != nil {
		mmPutObject.inspectFuncPutObject(ctx, bucketName, objectName, reader, objectSize, opts)
	}

	mm_params := &IMinioClientMockPutObjectParams{ctx, bucketName, objectName, reader, objectSize, opts}

	// Record call args
	mmPutObject.PutObjectMock.mutex.Lock()
	mmPutObject.PutObjectMock.callArgs = append(mmPutObject.PutObjectMock.callArgs, mm_params)
	mmPutObject.PutObjectMock.mutex.Unlock()

	for _, e := range mmPutObject.PutObjectMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmPutObject.PutObjectMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPutObject.PutObjectMock.defaultExpectation.Counter, 1)
		mm_want := mmPutObject.PutObjectMock.defaultExpectation.params
		mm_got := IMinioClientMockPutObjectParams{ctx, bucketName, objectName, reader, objectSize, opts}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPutObject.t.Errorf("IMinioClientMock.PutObject got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPutObject.PutObjectMock.defaultExpectation.results
		if mm_results == nil {
			mmPutObject.t.Fatal("No results are set for the IMinioClientMock.PutObject")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmPutObject.funcPutObject != nil {
		return mmPutObject.funcPutObject(ctx, bucketName, objectName, reader, objectSize, opts)
	}
	mmPutObject.t.Fatalf("Unexpected call to IMinioClientMock.PutObject. %v %v %v %v %v %v", ctx, bucketName, objectName, reader, objectSize, opts)
	return
}

// PutObjectAfterCounter returns a count of finished IMinioClientMock.PutObject invocations
func (mmPutObject *IMinioClientMock) PutObjectAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutObject.afterPutObjectCounter)
}

// PutObjectBeforeCounter returns a count of IMinioClientMock.PutObject invocations
func (mmPutObject *IMinioClientMock) PutObjectBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutObject.beforePutObjectCounter)
}

// Calls returns a list of arguments used in each call to IMinioClientMock.PutObject.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPutObject *mIMinioClientMockPutObject) Calls() []*IMinioClientMockPutObjectParams {
	mmPutObject.mutex.RLock()

	argCopy := make([]*IMinioClientMockPutObjectParams, len(mmPutObject.callArgs))
	copy(argCopy, mmPutObject.callArgs)

	mmPutObject.mutex.RUnlock()

	return argCopy
}

// MinimockPutObjectDone returns true if the count of the PutObject invocations corresponds
// the number of defined expectations
func (m *IMinioClientMock) MinimockPutObjectDone() bool {
	for _, e := range m.PutObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PutObjectMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPutObjectCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPutObject != nil && mm_atomic.LoadUint64(&m.afterPutObjectCounter) < 1 {
		return false
	}
	return true
}

// MinimockPutObjectInspect logs each unmet expectation
func (m *IMinioClientMock) MinimockPutObjectInspect() {
	for _, e := range m.PutObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IMinioClientMock.PutObject with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PutObjectMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPutObjectCounter) < 1 {
		if m.PutObjectMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IMinioClientMock.PutObject")
		} else {
			m.t.Errorf("Expected call to IMinioClientMock.PutObject with params: %#v", *m.PutObjectMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPutObject != nil && mm_atomic.LoadUint64(&m.afterPutObjectCounter) < 1 {
		m.t.Error("Expected call to IMinioClientMock.PutObject")
	}
}

type mIMinioClientMockRemoveObject struct {
	mock               *IMinioClientMock
	defaultExpectation *IMinioClientMockRemoveObjectExpectation
	expectations       []*IMinioClientMockRemoveObjectExpectation

	callArgs []*IMinioClientMockRemoveObjectParams
	mutex    sync.RWMutex
}

// IMinioClientMockRemoveObjectExpectation specifies expectation struct of the iMinioClient.RemoveObject
type IMinioClientMockRemoveObjectExpectation struct {
	mock    *IMinioClientMock
	params  *IMinioClientMockRemoveObjectParams
	results *IMinioClientMockRemoveObjectResults
	Counter uint64
}

// IMinioClientMockRemoveObjectParams contains parameters of the iMinioClient.RemoveObject
type IMinioClientMockRemoveObjectParams struct {
	ctx        context.Context
	bucketName string
	objectName string
	opts       minio.RemoveObjectOptions
}

// IMinioClientMockRemoveObjectResults contains results of the iMinioClient.RemoveObject
type IMinioClientMockRemoveObjectResults struct {
	err error
}

// Expect sets up expected params for iMinioClient.RemoveObject
func (mmRemoveObject *mIMinioClientMockRemoveObject) Expect(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions) *mIMinioClientMockRemoveObject {
	if mmRemoveObject.mock.funcRemoveObject != nil {
		mmRemoveObject.mock.t.Fatalf("IMinioClientMock.RemoveObject mock is already set by Set")
	}

	if mmRemoveObject.defaultExpectation == nil {
		mmRemoveObject.defaultExpectation = &IMinioClientMockRemoveObjectExpectation{}
	}

	mmRemoveObject.defaultExpectation.params = &IMinioClientMockRemoveObjectParams{ctx, bucketName, objectName, opts}
	for _, e := range mmRemoveObject.expectations {
		if minimock.Equal(e.params, mmRemoveObject.defaultExpectation.params) {
			mmRemoveObject.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRemoveObject.defaultExpectation.params)
		}
	}

	return mmRemoveObject
}

// Inspect accepts an inspector function that has same arguments as the iMinioClient.RemoveObject
func (mmRemoveObject *mIMinioClientMockRemoveObject) Inspect(f func(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions)) *mIMinioClientMockRemoveObject {
	if mmRemoveObject.mock.inspectFuncRemoveObject != nil {
		mmRemoveObject.mock.t.Fatalf("Inspect function is already set for IMinioClientMock.RemoveObject")
	}

	mmRemoveObject.mock.inspectFuncRemoveObject = f

	return mmRemoveObject
}

// Return sets up results that will be returned by iMinioClient.RemoveObject
func (mmRemoveObject *mIMinioClientMockRemoveObject) Return(err error) *IMinioClientMock {
	if mmRemoveObject.mock.funcRemoveObject != nil {
		mmRemoveObject.mock.t.Fatalf("IMinioClientMock.RemoveObject mock is already set by Set")
	}

	if mmRemoveObject.defaultExpectation == nil {
		mmRemoveObject.defaultExpectation = &IMinioClientMockRemoveObjectExpectation{mock: mmRemoveObject.mock}
	}
	mmRemoveObject.defaultExpectation.results = &IMinioClientMockRemoveObjectResults{err}
	return mmRemoveObject.mock
}

// Set uses given function f to mock the iMinioClient.RemoveObject method
func (mmRemoveObject *mIMinioClientMockRemoveObject) Set(f func(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions) (err error)) *IMinioClientMock {
	if mmRemoveObject.defaultExpectation != nil {
		mmRemoveObject.mock.t.Fatalf("Default expectation is already set for the iMinioClient.RemoveObject method")
	}

	if len(mmRemoveObject.expectations) > 0 {
		mmRemoveObject.mock.t.Fatalf("Some expectations are already set for the iMinioClient.RemoveObject method")
	}

	mmRemoveObject.mock.funcRemoveObject = f
	return mmRemoveObject.mock
}

// When sets expectation for the iMinioClient.RemoveObject which will trigger the result defined by the following
// Then helper
func (mmRemoveObject *mIMinioClientMockRemoveObject) When(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions) *IMinioClientMockRemoveObjectExpectation {
	if mmRemoveObject.mock.funcRemoveObject != nil {
		mmRemoveObject.mock.t.Fatalf("IMinioClientMock.RemoveObject mock is already set by Set")
	}

	expectation := &IMinioClientMockRemoveObjectExpectation{
		mock:   mmRemoveObject.mock,
		params: &IMinioClientMockRemoveObjectParams{ctx, bucketName, objectName, opts},
	}
	mmRemoveObject.expectations = append(mmRemoveObject.expectations, expectation)
	return expectation
}

// Then sets up iMinioClient.RemoveObject return parameters for the expectation previously defined by the When method
func (e *IMinioClientMockRemoveObjectExpectation) Then(err error) *IMinioClientMock {
	e.results = &IMinioClientMockRemoveObjectResults{err}
	return e.mock
}

// RemoveObject implements miniorepo.iMinioClient
func (mmRemoveObject *IMinioClientMock) RemoveObject(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions) (err error) {
	mm_atomic.AddUint64(&mmRemoveObject.beforeRemoveObjectCounter, 1)
	defer mm_atomic.AddUint64(&mmRemoveObject.afterRemoveObjectCounter, 1)

	if mmRemoveObject.inspectFuncRemoveObject != nil {
		mmRemoveObject.inspectFuncRemoveObject(ctx, bucketName, objectName, opts)
	}

	mm_params := &IMinioClientMockRemoveObjectParams{ctx, bucketName, objectName, opts}

	// Record call args
	mmRemoveObject.RemoveObjectMock.mutex.Lock()
	mmRemoveObject.RemoveObjectMock.callArgs = append(mmRemoveObject.RemoveObjectMock.callArgs, mm_params)
	mmRemoveObject.RemoveObjectMock.mutex.Unlock()

	for _, e := range mmRemoveObject.RemoveObjectMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRemoveObject.RemoveObjectMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRemoveObject.RemoveObjectMock.defaultExpectation.Counter, 1)
		mm_want := mmRemoveObject.RemoveObjectMock.defaultExpectation.params
		mm_got := IMinioClientMockRemoveObjectParams{ctx, bucketName, objectName, opts}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRemoveObject.t.Errorf("IMinioClientMock.RemoveObject got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRemoveObject.RemoveObjectMock.defaultExpectation.results
		if mm_results == nil {
			mmRemoveObject.t.Fatal("No results are set for the IMinioClientMock.RemoveObject")
		}
		return (*mm_results).err
	}
	if mmRemoveObject.funcRemoveObject != nil {
		return mmRemoveObject.funcRemoveObject(ctx, bucketName, objectName, opts)
	}
	mmRemoveObject.t.Fatalf("Unexpected call to IMinioClientMock.RemoveObject. %v %v %v %v", ctx, bucketName, objectName, opts)
	return
}

// RemoveObjectAfterCounter returns a count of finished IMinioClientMock.RemoveObject invocations
func (mmRemoveObject *IMinioClientMock) RemoveObjectAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRemoveObject.afterRemoveObjectCounter)
}

// RemoveObjectBeforeCounter returns a count of IMinioClientMock.RemoveObject invocations
func (mmRemoveObject *IMinioClientMock) RemoveObjectBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRemoveObject.beforeRemoveObjectCounter)
}

// Calls returns a list of arguments used in each call to IMinioClientMock.RemoveObject.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRemoveObject *mIMinioClientMockRemoveObject) Calls() []*IMinioClientMockRemoveObjectParams {
	mmRemoveObject.mutex.RLock()

	argCopy := make([]*IMinioClientMockRemoveObjectParams, len(mmRemoveObject.callArgs))
	copy(argCopy, mmRemoveObject.callArgs)

	mmRemoveObject.mutex.RUnlock()

	return argCopy
}

// MinimockRemoveObjectDone returns true if the count of the RemoveObject invocations corresponds
// the number of defined expectations
func (m *IMinioClientMock) MinimockRemoveObjectDone() bool {
	for _, e := range m.RemoveObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RemoveObjectMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRemoveObjectCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRemoveObject != nil && mm_atomic.LoadUint64(&m.afterRemoveObjectCounter) < 1 {
		return false
	}
	return true
}

// MinimockRemoveObjectInspect logs each unmet expectation
func (m *IMinioClientMock) MinimockRemoveObjectInspect() {
	for _, e := range m.RemoveObjectMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IMinioClientMock.RemoveObject with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RemoveObjectMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRemoveObjectCounter) < 1 {
		if m.RemoveObjectMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IMinioClientMock.RemoveObject")
		} else {
			m.t.Errorf("Expected call to IMinioClientMock.RemoveObject with params: %#v", *m.RemoveObjectMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRemoveObject != nil && mm_atomic.LoadUint64(&m.afterRemoveObjectCounter) < 1 {
		m.t.Error("Expected call to IMinioClientMock.RemoveObject")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IMinioClientMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockPresignedGetObjectInspect()

		m.MinimockPutObjectInspect()

		m.MinimockRemoveObjectInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IMinioClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IMinioClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPresignedGetObjectDone() &&
		m.MinimockPutObjectDone() &&
		m.MinimockRemoveObjectDone()
}
